### ISSUE TITLE
Graft editor shows same superscript letter for two consecutive footnotes

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-editor#66]
@mandolyte commented on [Tue Feb 07 2023](https://github.com/unfoldingWord/gateway-translate/issues/139)

To replicate:
1. login and select the book of Ruth
2. Go to chapter 4, verse 4.
3. Select footnote "a". This will show:
![image](https://user-images.githubusercontent.com/1289437/217246983-5829bab7-53ab-49e8-b788-a5ae09cf22fd.png)
4. Close it and select footnote "b". This will show:
![image](https://user-images.githubusercontent.com/1289437/217247120-ab5200b8-79a2-446c-9114-23dbcb0cdf8c.png)
5. Note that both are shown as footnote "a".

Footnote "b" should show as "b", not "a".

**Comment by klappy** [comment]
For context, it is important to know how the superscript graft elements are created visually. They do not exist and are injected via CSS ::before or ::after that auto-increments based on how many are visible on the screen.

Secondly, it is more important to know that the A and A examples are referring to nested grafts in which aren’t even suppose to be A and B. They are sub-grafts or links to entities that are not visible on the screen. The funny thing is… the nested graft just happens to be the footnote attribute that is suppose to display in the place of A and B, which is just coincidental. 

So there needs to be some design behind how to address this issue as it isn’t a bug, it is working as designed. This is an edge case which has been known from the beginning but using the 80/20 rule, we punted.

**Comment by mandolyte** [comment]
@klappy @birchamp 

The superscripts are consecutive letters. If I edit the footnote markers by inserting a single space between them, this will correct the problem.

@klappy Given this how do you think the CSS should be adjusted?

**Comment by mandolyte** [comment]
@klappy Well the CSS idea didn't work... so the problem is deeper as you thought.

[Screen recording 2023-03-10 8.23.22 AM.webm](https://user-images.githubusercontent.com/1289437/224327749-14d67f0e-593e-4aaf-84b1-46527d2b2567.webm)

**Comment by klappy** [comment]
<@868198023967174687> if you put the pop-up graft editor in preview mode, by adding a parent class of .preview that should fix the nested view with the appropriate superscript that is in the graft’s data-text attribute. This might only be necessary on certain grafts through logic but I’m guessing I’d err on the simple solution. 

There is one other solution that I’m also keen to solve this with 100% css as it is powerful enough to do it. If you can create an easy way for me to recreate and see the problem, I can take a crack at it as it should only take me about 15m or so. I can have a css query for the appropriate item as it’s usually not visible at the book’s main graft but available when the nested graft editor opens the footnote graft.

**Comment by klappy** [comment]
Okay, it looks like we are already in preview mode and that is where the issue is coming into play... 
If we modify the current query that does what we want to also override .note_caller in .preview mode we modify this:
```css
.perf span.graft:after {
    content: " " attr(data-previewtext);
    -webkit-text-decoration: underline wavy #d3d3d3;
    text-decoration: underline wavy #d3d3d3;
}
```
Into this:
```css
.perf span.graft:after, .perf .preview span.note_caller:after {
    content: " " attr(data-previewtext);
    -webkit-text-decoration: underline wavy #d3d3d3;
    text-decoration: underline wavy #d3d3d3;
}
```
